### ISSUE TITLE
Support to coerce anova.lm.rrpp to a data.frame for integration with knitr

### ISSUE THREAD

**Issue by drpradeepharish** [mlcollyer/RRPP#11]
Is it possible to coerce a lm.rrpp object to a data.frame / other type that is supported by knitr to export the data in a pretty table please?

```
library(tidyverse)
library(knitr)
library(kableExtra)
library(rrpp)

rrppModelFit <-
  lm.rrpp(
    distanceSummaryData ~ condition, #
    data = rrppSummaryData,
    block = rrppSummaryData$patient_id,
    iter = 10,
    parallel = 12,
    SS.type = "I",
    turbo = FALSE
  )

anova.lm.rrpp(rrppModelFit) %>% knitr() 
```

outputs
> Error in as.data.frame.default(x) : 
  cannot coerce class ‘"anova.lm.rrpp"’ to a data.frame

**Comment by drpradeepharish** [comment]
Solved as 

`anova.lm.rrpp(rrppModelFit) %>% .$table %>% kable()`

**Comment by mlcollyer** [comment]
If your goal is to have a data frame for ANOVA output, no coercion is needed.  The $table output is already a data.frame object.  This should work:

anova(rrppModelFit)$table %>% knitr() 
A class anova.lm.rrpp object is a list with the following attributes:

$names
[1] "table"       "perm.method" "perm.number" "est.method"  "SS.type"     "effect.type"
[7] "call”       

I think you are expecting the table to be the only output.

Best,
Mike

**Comment by drpradeepharish** [comment]
> list with the following attributes:

Yep, just realised that after I posted the issue. Hence closed it with utmost speed :P

Sorry for the bother, and thank you for your work on the package. Really appreciate it.

**Comment by mlcollyer** [comment]
No worries, and you’re welcome!
