### ISSUE TITLE
coef() function returns NULL when using gls estimation

### ISSUE THREAD

**Issue by jjustison** [mlcollyer/RRPP#4]
Not sure if this is intended or not but the `coef()` function returns `NULL` for some `lm.rrpp` objects. I think this has to do with using a `Cov` argument and using GLS for estimation. For example:

```
data("PlethMorph")
fitOLS <- lm.rrpp(TailLength ~ SVL, data = PlethMorph, 
                  print.progress = FALSE, iter = 999)
fitGLS <- lm.rrpp(TailLength ~ SVL, data = PlethMorph, Cov = PlethMorph$PhyCov, 
                  print.progress = FALSE, iter = 999)

coef(fitOLS) ##Returns coefficients as expected
coef(fitGLS) ##Returns NULL
```
I think this has to do with how the estimates are saved. The OLS approach saves the coefficients in `fitOLS$LM$coefficients` while   the GLS approach saves the coefficients under `fitGLS$LM$gls.coefficients`

**Comment by mlcollyer** [comment]
Hello,

Thanks for catching this!  Originally, we $LM$coefficients, regardless of whether the estimation was OLS or GLS, but updated the function to remind users that the coefficients were estimated via GLS.  It looks like we forgot to extend this to the coef.lm.rrpp function.  I will fix it soon.  In the interim, if you choose test = TRUE, the print.coef.lm.rrpp function will provide the coefficients (along with test statistics).

Cheers!
Mike

**Comment by mlcollyer** [comment]
This is fixed now!
