### ISSUE TITLE
could not find function "scaleCov"

### ISSUE THREAD

**Issue by StanleeKol** [mlcollyer/RRPP#5]
I am trying to run geomorph function "procD.pgls but I keep getting "Error in scaleCov(Cov, scale. = lambda) : 
  could not find function "scaleCov""
Please, do you have any suggestion? I run the library RRPP.
Thanks.

UPDATE--I reinstalled package and it works, I am sorry for spam.

**Comment by mlcollyer** [comment]
You might have an older version of RRPP. Try updating to the most recent version. 

Mike
