### ISSUE TITLE
Error when "print.progress = T" in trajectory.analysis

### ISSUE THREAD

**Issue by aConar** [mlcollyer/RRPP#8]
Dear Michael, I noticed that when print.progress is se to True in trajectory.analysis the following error show up:
`Error in setTxtProgressBar(pb, step) : object 'pb' not found`
Setting  "print.progress = F" works fine. I'm running Linux, maybe a missing library?
Another  question related to  trajectory.analysis. Playing with the example data Pupfish if I run:
`plot(gm.prcomp(Pupfish$coords))`
I get a PCA plot where the first PC has a 43% of total variance. But when plotting the trajectory.analysis of same data:
```
TP <- plot(TA, pch = as.numeric(Pupfish$Pop) + 20, bg = as.numeric(Pupfish$Sex), cex = 0.7, col = "gray")
add.trajectories(TP, traj.pch = c(21, 22), start.bg = 1, end.bg = 2)
```
The 1st PC shows 62% of total variance. Is that correct?
Thanks in advance.
Ale

**Comment by mlcollyer** [comment]
Dear Ale,

Thanks for the alert!  I fixed a bug (actually in pairwise) that had an illogical print.progress condition.  This fix has been pushed to github.

Regarding your second question, the PCAs are performed on different values, as made clear in the axes of the plot in the trajectory plot (fitted values, not data), as well as the help file.

Best,
Mike
